- pyproject.toml
- src/fromager/__main__.py
- tox.ini
> add 'fromager' console script

- README.md
> add naming section to readme

- .mergify.yml
> require bootstrap job

- .mergify.yml
> switch rules for e2e jobs to use pending parameterized names

- .github/workflows/test.yaml
- .mergify.yml
- e2e/test_report_missing_dependency.sh
- src/fromager/sdist.py
> end-to-end test for reporting a missing dependency

- .github/workflows/check.yaml
- .gitignore
- .mergify.yml
- pyproject.toml
- tox.ini
> set up pkglint

- docs/customization.md
- src/fromager/__main__.py
> accept any string as a build variant

- .github/workflows/python-publish.yaml
- pyproject.toml
- tox.ini
> set up automated publishing

- e2e/test_bootstrap.sh
- src/fromager/context.py
Write a constraints file in a format consumable by pip.
> feature: write a constraints.txt file next to build-order.json

- src/fromager/overrides.py
Die if we find a plugin but can't import it. This ensures we don't
silently ignore errors in the plugin modules.
Improve debug message when we just don't find a plugin, showing which
ones we do find.
Log when we do find an override so it's clear which path we're taking.
> improve debugging when plugins do not load

- src/fromager/sources.py
Look at the function signature for extractall() to see if it takes the
'filter' argument before passing it.
Fixes #69
> only pass filter to extractall() when supported

- src/fromager/__main__.py
- src/fromager/commands/bootstrap.py
- src/fromager/commands/build.py
- src/fromager/commands/build_order.py
- src/fromager/commands/canonicalize.py
- src/fromager/commands/download_sequence.py
- src/fromager/commands/step.py
- src/fromager/context.py
- src/fromager/dependencies.py
- src/fromager/example_override.py
- src/fromager/external_commands.py
- src/fromager/finders.py
- src/fromager/overrides.py
- src/fromager/resolver.py
- src/fromager/sdist.py
- src/fromager/server.py
- src/fromager/settings.py
- src/fromager/sources.py
- src/fromager/tarballs.py
- src/fromager/wheels.py
- tests/conftest.py
Update most of the application code with type annotations.
> add type annotations to application code

- src/fromager/overrides.py
Wait to load the override extensions until they're needed so that more of fromager will be imported and if the plugins import from fromager they won't trigger circular import errors.
Fixes #122
> avoid circular imports in override plugins

- README.md
> document netrc configuration for private repository access

- pyproject.toml
- tests/test_dependencies.py
Add some unit tests that pull the dependencies of fromager itself.
> expand test coverage for fromager.dependencies

- src/fromager/__main__.py
- src/fromager/constraints.py
- src/fromager/context.py
- src/fromager/sdist.py
- tests/conftest.py
- tests/test_constraints.py
- tests/test_sdist.py
Part of #102 
Implements a simple constraints list where user is only allowed to use "==" constraints. Ensures that the given constraint version is not in conflict with the required version.
> Add implementation for a basic constraints file

- src/fromager/commands/__init__.py
- src/fromager/commands/list_overrides.py
- src/fromager/overrides.py
- tests/test_overrides.py
Provide a command to list all of the known
overrides of any sort in the current
configuration.
Fixes #135
> add list-overrides command

- src/fromager/context.py
- src/fromager/sdist.py
- tests/test_context.py
> Add `constrained_req` field to build order

- src/fromager/commands/build_order.py
Add a command to show any duplicates in a
build-order.json file to help understand potential
conflicts. Include an option for showing only the
installation-time requirements, since build
requirements are installed in isolation.
Sample output:
```
$ fromager build-order show-duplicates ../builder/bootstrap-output.cuda-ubi9/work-dir/build-order.json 
cython: building 3 versions
'Cython' resolved to 3.0.10 as a build-backend dependency of datasets>=2.18.0, aiohttp, aiosignal>=1.1.2, frozenlist>=1.1.0
'Cython<3.0' resolved to 0.29.37 as a build-system dependency of datasets>=2.18.0, huggingface-hub>=0.21.2, pyyaml>=5.1
'Cython==3.0.5' resolved to 3.0.5 as a build-system dependency of datasets>=2.18.0, pandas
fsspec: building 2 versions
'fsspec[http]<=2024.5.0,>=2023.1.0' resolved to 2024.5.0 …
```
> add build-order show-duplicates command

- src/fromager/commands/__init__.py
- src/fromager/commands/server.py
- src/fromager/overrides.py
- src/fromager/server.py
> add command to start local wheel server

- src/fromager/commands/bootstrap.py
- src/fromager/constraints.py
- src/fromager/requirements_file.py
- tests/test_bootstrap.py
- tests/test_constraints.py
- tests/test_requirements_file.py
From: https://github.com/python-wheel-build/fromager/pull/144#discussion_r1667184891
Refactoring out the requirement file parsing done in bootstrap.py so that it can be used in constraints.py
> Refactor requirement file parsing

- src/fromager/sdist.py
- src/fromager/sources.py
- tests/test_sdist.py
- tests/test_sources.py
Final version of changes as per the discussion : https://github.com/python-wheel-build/fromager/pull/160
(`sdist.py` had enough changes to cause merge conflicts and leading me to create another PR)
> Adding checks for downloaded source and tar files

- src/fromager/wheels.py
Changes as per suggestion in https://github.com/python-wheel-build/fromager/pull/192#pullrequestreview-2183301298
> This commit adds code to calculate time taken to build a wheel

- src/fromager/sources.py
- tests/test_sources.py
Let me know if changes are required
> Validating return value of version from download_source()

- src/fromager/dependencies.py
- src/fromager/finders.py
- src/fromager/overrides.py
- src/fromager/sources.py
- src/fromager/wheels.py
- tests/test_overrides.py
> feat: add implementation of invoke function

- tox.ini
This PR is for the issue: https://github.com/python-wheel-build/fromager/issues/172
I am new to writing workflows, CI and GitHub actions so not sure whether what I have done in this PR is correct. Please let me know if any changes are required
> Restoring mergify_linter in CI

- tests/test_sources.py
As requested here: https://github.com/python-wheel-build/fromager/pull/205
> Fixing the failing unit tests

- .github/workflows/test.yaml
- .mergify.yml
- e2e/test_optimize_build.sh
- src/fromager/sdist.py
- tests/test_sources.py
As per changes and discussion here: https://github.com/python-wheel-build/fromager/pull/173
> optimizing sdist production during bootstrapping

- src/fromager/constraints.py
Fixes : https://github.com/python-wheel-build/fromager/issues/213
> This commit adds constraints present in build order to constraints.txt

- pyproject.toml
- requirements-build.txt
- requirements-test.txt
- requirements.txt
Having the requirements lists in separate files
makes it easier to automate keeping them up to
date.
> create separate requirements files

- src/fromager/overrides.py
part of #226 
fixes the following errors:
```
src/fromager/overrides.py:36: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/overrides.py:44: error: Missing type parameters for generic type "typing.Callable"  [type-arg]
src/fromager/overrides.py:44: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/overrides.py:44: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src/fromager/overrides.py:46: error: Function "fn" could always be true in boolean context  [truthy-function]
src/fromager/overrides.py:51: error: Missing type parameters for generic type "typing.Callable"  [type-arg]
src/fromager/overrides.py:51: error: Function is missing a return type annotation  [no-untyped-def] …
```
> cleanup: fix typings in overrides.py

- src/fromager/tarballs.py
As part of cleanup: https://github.com/python-wheel-build/fromager/issues/226
> This commit fixes mypy errors in file tarballs.py

- src/fromager/overrides.py
part of #226 
incorrect kwargs type from #237  results in more errors in other modules
> cleanup: fix kwargs typing

- src/fromager/sources.py
- tests/test_sources.py
Fixes: https://github.com/python-wheel-build/fromager/issues/202
> This commit warns if patches for older versions exists

- src/fromager/server.py
As part of: https://github.com/python-wheel-build/fromager/issues/226
> This commit attempts to fix mypy errors in file server.py

- src/fromager/settings.py
As part of: https://github.com/python-wheel-build/fromager/issues/226
> Fix mypy errors in settings.py

- requirements.txt
- src/fromager/dependencies.py
- src/fromager/vendor_rust.py
tomlkit preserves comments and document layout.
> Switch from toml to tomlkit

- docs/customization.md
- src/fromager/commands/step.py
- src/fromager/finders.py
- src/fromager/sdist.py
- src/fromager/settings.py
- src/fromager/sources.py
- tests/test_finders.py
- tests/test_settings.py
- tests/test_sources.py
> feat: source finders should be aware of download config settings

- src/fromager/overrides.py
- src/fromager/sources.py
- tests/test_overrides.py
- tests/test_sources.py
Fixes: https://github.com/python-wheel-build/fromager/issues/254
Also, I have used the test case suggested by @shubhbapna which was failing
> bug fix: warning for old patches

- e2e/flit_core_patches/flit_core/flit_core.patch
- e2e/test_override.sh
- src/fromager/external_commands.py
- src/fromager/sources.py
- tests/test_external_commands.py
> fix: use external_commands.run to apply patch

- src/fromager/sources.py
> fix: expose `default_patch_source` and return `is_new`

- docs/customization.md
- src/fromager/overrides.py
- tests/test_overrides.py
> support env files not tied to a variant

- src/fromager/settings.py
- tests/test_settings.py
> feat: add changelog field to settings

- src/fromager/commands/download_sequence.py
> download-sequence: log an optionally ignore errors downloading sdists

- src/fromager/wheels.py
`add_extra_metadata_to_wheels()` was using the normalized distribution name to locate the wheel's `.dist-info` directory. However the `.dist-info` directory uses the verbatim distribution name from the wheel file name, e.g. `MarkupSafe-2.1.5.dist-info`.
Fromager now uses the correct naming convention. The whee build step fails if the expected `.dist-info` is missing.
> Fix extra metadata for packages with non-canonical names

- src/fromager/wheels.py
Fixes: https://github.com/python-wheel-build/fromager/issues/339
> Adding `dist_info_dir` to `add_extra_metadata_to_wheels`

- src/fromager/commands/build.py
- src/fromager/sdist.py
- src/fromager/settings.py
- src/fromager/wheels.py
- tests/test_settings.py
> feat: add global changelog to trigger rebuilds of all packages with new build tag

- docs/customization.md
> docs: add docs on changelog, extra metada for wheels and speeding up build-sequence

- src/fromager/commands/bootstrap.py
- src/fromager/context.py
- src/fromager/requirements_file.py
- src/fromager/sdist.py
- tests/test_bootstrap.py
- tests/test_sdist.py
> fix: change req_type from string to enum

- src/fromager/commands/download_sequence.py
- src/fromager/sdist.py
- src/fromager/wheels.py
> fix: decouple wheel resolution from downloading of the wheel file

- .github/workflows/test.yaml
- .mergify.yml
- docs/customization.md
- e2e/test_bootstrap_prerelease.sh
- src/fromager/constraints.py
- src/fromager/resolver.py
> backport: allow prereleases and update docs for skipping downloading of prebuilt wheels

- docs/files.md
- docs/index.rst
JIRA: https://issues.redhat.com/browse/RHELAI-1056
Fixes: https://github.com/python-wheel-build/fromager/issues/292
> RHELAI-1056: Document formats of input and output files

- src/fromager/dependency_graph.py
- src/fromager/sdist.py
- tests/test_bootstrap.py
- tests/test_graph.py
> add pre_built datatype to node and more methods to graph

- src/fromager/resolver.py
- tests/test_resolver.py
part of #389 
Also adds a function to resolve when given a provider.
> fix url in version source for generic provider

- e2e/test_report_missing_dependency.sh
- src/fromager/context.py
- src/fromager/sdist.py
- tests/test_context.py
> fix: remove type from build-order

- src/fromager/commands/download_sequence.py
> fix: download-sequence store prebuilts in the prebuilt directory

- src/fromager/commands/bootstrap.py
- src/fromager/sdist.py
- src/fromager/wheels.py
- tests/test_sdist.py
> feat: allow dependency resolution using the result of a previous bootstrap

- src/fromager/__main__.py
- src/fromager/commands/bootstrap.py
- src/fromager/commands/build.py
- src/fromager/commands/download_sequence.py
- src/fromager/packagesettings.py
- src/fromager/requirements_file.py
Report about the inputs to main and bootstrap.
Report more details about pre-build steps in
build-sequence.
Report reading requirements and build-order files.
> add more info logging

- e2e/test_build_order.sh
- src/fromager/__main__.py
- src/fromager/commands/build.py
- src/fromager/context.py
This commit is related to per wheel log feature for the `build-sequence` command
JIRA Epic: https://issues.redhat.com/browse/RHELAI-1323
JIRA ticket: https://issues.redhat.com/browse/RHELAI-1487
References:
- https://docs.python.org/3/library/logging.html#logging.Logger.addHandler
> Feat: Per wheel log

- src/fromager/__main__.py
- src/fromager/commands/bootstrap.py
- src/fromager/commands/build.py
> only show build settings for build commands

- e2e/test_build_order.sh
- e2e/test_build_steps.sh
- e2e/test_pep517_build_sdist.sh
- e2e/test_prebuilt_wheels_alt_server.sh
- e2e/test_report_missing_dependency.sh
- src/fromager/__main__.py
- src/fromager/commands/build.py
- src/fromager/commands/step.py
- src/fromager/context.py
- tests/conftest.py
- tests/test_context.py
fixes #423 
remove wheel-server-url arg from all commands except `fromager step build-wheel`, `fromager step prepare-build` and `fromager build`
> remove `--wheel-server-url` arg

- src/fromager/wheels.py
- tests/test_wheels.py
> check whether downloaded wheel is valid or not

- src/fromager/wheels.py
> set the permission bits when unpacking a wheel

- e2e/test_build_order.sh
- src/fromager/commands/build.py
fixes #505 
build-sequence will behave like make now where by default it doesn't build wheels if it has already been built. We can change this by passing the `--force` flag which will cause fromager to rebuild all wheels.
To check if a wheel has already been built, fromager looks only in the local pypi server it spins up. we can check an additional external server by passing the `--cache-wheel-server-url` option.
> add `--cache-wheel-server-url` and `--force` options to build-sequence

- .mergify.yml
- CODEOWNERS
Add the maintainers team to the CODEOWNERS file to ensure a member of the team reviews all PRs.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> set up CODEOWNERS

- .github/workflows/check.yaml
- .github/workflows/test.yaml
- pyproject.toml
- tests/test_dependencies.py
> Hatch cleanup

- src/fromager/commands/__init__.py
- src/fromager/commands/stats.py
- src/fromager/constraints.py
- tests/test_stats_command.py
This PR adds a new `stats` command to fromager that provides detailed statistics about package builds. The command analyzes a requirements file and dependency graph to show various metrics about the packages involved in a build.
The `stats` command takes two arguments:
- `requirements_file`: A requirements.txt file used for the build
- `graph_file`: A fromager graph.json file produced by the build
It displays a formatted table showing:
- **Requirements in requirements.txt**: Count of packages in the input requirements file
- **Constraints defined**: Total number of version constraints in the build configuration
- **Unique packages in build**: Total packages in the dependency graph (100% baseline)
- **Packages in the build with constraints**: How many built packages have version …
> add stats command

- src/fromager/candidate.py
- src/fromager/resolver.py
- tests/test_pep658_support.py
- tests/test_resolver.py
This commit is my attempt to add support for PEP 658 which looks for Metadata URL while resolution
Further, this commit also adds unit tests to test this functionality
Fixes https://github.com/python-wheel-build/fromager/issues/360
> [Feat]: Add support for PEP 658 Metadata

- src/fromager/commands/build.py
- log built nodes in case of an error
- log which nodes get submitted to thread pool worker
- annotate several lists and sets
> fix: improve logging and type annotations of build-parallel

- src/fromager/commands/build.py
`build_nodes` is not a set of dependency nodes. It is a set of dependency node keys `set[str]`. Fix the error message and type annotation.
> fix: fix circular error debug message

- src/fromager/commands/build.py
Improve logging in the build-parallel command to make it clear why some packages can start building and others cannot.
Sort the nodes to be built so that the loop processes them in a deterministic order. This should not affect the actual build order, but it makes it easier to compare log output and to find packages in the output because the names are sorted.
Fix up some type annotations that were wrong or confused the linter.
> fix: improve logging in build-parallel

- src/fromager/commands/build.py
Update the progress bar immediately after a future task has completed. Before the progress bar was updated after all tasks in the current batch have been completed. A batch can have dozens of tasks.
> Update progress bar in future done callback

- src/fromager/bootstrapper.py
A long-running bootstrap job may resolve the same requirements specifier many times, especially for packages like setuptools or flit-core. This change adds a cache for all requirements based on their full spec so that if we see the same string more than once we give the same value without going out to the server to look at available packages again.
> feat: add cache to resolver in bootstrapper

- src/fromager/dependencies.py
Add an override for determining the installation dependencies of a package from its sdist. The existing implementation remains the default, but plugins can modify values like the build directory or environment settings.
> feat: make get_install_dependencies_of_sdist pluggable

- src/fromager/build_environment.py
A `BuildEnvironment` object has new methods to get sysconfig path (e.g. `platlib` directory) and a mapping of installed packages and their versions.
The information is needed for downstream packaging, e.g. to get the current Torch version to add correct constraint `PYTORCH_VERSION` constraint to TorchAudio and TorchVision.
> feat: get installed packages and syspath from BuildEnvironment

- src/fromager/bootstrapper.py
- tests/test_wheels.py
Latest Ruff complains about unused variables in two files.
> fix: address Ruff errors in existing code

- src/fromager/pyproject.py
- tests/test_pyproject.py
The project_override feature was incorrectly overwriting requirements when the same package appeared multiple times with different version constraints.
Fixes: #655
> fix: preserve multiple requirements with markers in project_override
