python-wheel-build/fromager

.github/workflows/test.yaml, .mergify.yml, e2e/flit_core_override/build/lib/package_plugins/flit_core.py, e2e/flit_core_override/pyproject.toml, e2e/flit_core_override/src/package_plugins/flit_core.py, e2e/test_bootstrap.sh, e2e/test_build_with_build_order.sh, e2e/test_override.sh, e2e/test_report_missing_dependency.sh, src/fromager/__main__.py, src/fromager/overrides.py, tox.ini
* add test to verify we load a build override properly
* update build order test
* on startup, log the override plugins found
* make build order test look for output files
=> e2e: extend end-to-end testing

tox.ini
Set the base_python to python3.11 for specialized environments so they
do not use an old version accidentally. Leave the default unset so
that the `py` environment picks up python3 from the $PATH to allow for
a newer version easily.
=> tox: set base_python to 3.11 for most envs

e2e/test_build_with_build_order.sh, e2e/test_report_missing_dependency.sh
Move to a different port to avoid collisions with cockpit on RHEL and
Fedora systems.
=> e2e: change port for local wheel server

.github/workflows/test.yaml, .mergify.yml, e2e/flit_core_override/pyproject.toml, pyproject.toml, tox.ini
SynapseAI / HabanaLabs 1.15 for Intel Gaudi is only available for Python 3.10.
=> Test on Python 3.10 for Intel Gaudi

pyproject.toml
We had some legacy commands using the gitlab API that are no longer
part of fromager.
=> drop python-gitlab dependency

docs/customization.md, src/fromager/__main__.py
Using a variable is easier when doing builds in containers.
=> feature: allow setting the variant via FROMAGER_VARIANT

e2e/test_bootstrap.sh, e2e/test_build_with_build_order.sh, src/fromager/wheels.py
When we run the step to build the wheel, tell pip to write a log file
in the directory above where the source is located. Using this
location ensures the file is preserved when bootstrap cleans up the
source tree, and makes it easy to collect all of the files if we are
building a sequence.
=> feature: log the output of the build command

pyproject.toml, src/fromager/wheels.py
It's not clear why, but the virtual environments created by the two tools
are different, at least for python3.11. This causes maturin to incorrectly
try to build rust dependencies using the python3 in
/usr/bin, instead of the one in the virtual environment.
One difference we noted is in the pyvenv.cfg files:
```
diff virtualenv.pyvenv.cfg venv.pyvenv.cfg 2,4d1
< implementation = CPython
< version_info = 3.11.7.final.0
< virtualenv = 20.26.2 6,8c3,5
< base-prefix = /usr
< base-exec-prefix = /usr
< base-executable = /usr/bin/python3.11
---
> version = 3.11.7
> executable = /usr/bin/python3.11
> command = /usr/bin/python3.11 -m venv --copies --clear
/work/bootstrap-output/work-dir/pydantic_core-2.18.4/build-3.11.7
```
=> use virtualenv instead of venv

.mergify.yml
Introducing rust into the test matrix changed the names of the jobs,
so update the auto-merge rules to reflect the new names. Also require
3.10 jobs to pass.
=> update the mergify rules to account for python 3.10 and rust 1.75

src/fromager/finders.py
A lot of package names produce the same values when canonicalized or
put through other transformations. This change avoids checking
redundant values.
=> limit the redundant checks in finders

.github/workflows/test.yaml, .mergify.yml, e2e/test_prebuilt_wheels_alt_server.sh, src/fromager/sdist.py, src/fromager/sources.py
When looking for a prebuilt wheel, if we've been given a
wheel-server-url via the command line flag ensure that we check that
server before looking at pypi.org. This allows users to host private
wheel repositories with some wheels and incorporate them into fromager
environments without having to publish those wheels to pypi.org.
=> feature: prefer our wheel server over pypi.org for prebuilt wheels

src/fromager/__main__.py, src/fromager/commands/bootstrap.py
Several commands need to know the variant so move it from the
bootstrap command to main and ensure it is configured on the context
all the time.
=> move --variant option to main

src/fromager/commands/build.py, src/fromager/commands/step.py, src/fromager/context.py, src/fromager/dependencies.py, src/fromager/sdist.py, src/fromager/sources.py, src/fromager/vendor_rust.py, src/fromager/wheels.py
Make the logs easier to follow by including the current requirement
being processed as a prefix for most log message lines.
=> include current package as prefix in log messages

.github/workflows/test.yaml, .mergify.yml, e2e/download_sequence/simplejson-build-order.json, e2e/test_download_sequence.sh, src/fromager/commands/__init__.py, src/fromager/commands/download_sequence.py
Implements `download-sequence` command and corresponding tests. Uses a `build-order.json` compiled for CPU for `simplejson==3.19.2`. Later on enablement / testing should be added for multiple sdist servers.
=> adding download sequence command

.gitignore, pyproject.toml, src/fromager/resolver.py, src/fromager/sdist.py, src/fromager/sources.py, tests/test_resolver.py, tests/test_sdist.py
Change the resolver code to have explicit options for whether to include
sdist and wheel distributions as candidates.
Rename sources.resolve_sdist() to sources.resolve_dist() to reflect the
scope change.
Add requests_mock testing dependency.
Fixes #87
=> let the resolver filter the type of distribution

src/fromager/sdist.py, src/fromager/sources.py
In a few places where we change the default inputs to resolve_dist()
pass both options for clarity about what sorts of distributions are
expected as results.
Related to #88
Related to #87
=> be more explicit about the types of dists to download

e2e/test_bootstrap.sh, e2e/test_build_order.sh, e2e/test_build_steps.sh
Some of the e2e jobs had hard-coded expectations for version numbers
of dependencies of packages involved in the tests. Those versions will
change over time as new releases are created, so this commit reworks
the tests to be more flexible about the version numbers and removes
the dependencies that have been dropped from the test packages.
=> make e2e jobs more robust

src/fromager/commands/bootstrap.py, tests/test_bootstrap.py
The CLI takes as input requirements or files with lists of requirements. This adds the filename as part of the build-order output and log messages so it is easier to understand where a requirement was fed into the system.
=> when bootstrapping, report origin of each requirement

README.md, e2e/run_all.sh, e2e/test_bootstrap.sh, e2e/test_build_steps.sh, pyproject.toml, src/fromager/commands/build.py, src/fromager/commands/step.py, src/fromager/context.py, src/fromager/dependencies.py, src/fromager/sdist.py, src/fromager/sources.py, src/fromager/tarballs.py, tests/test_tarballs.py
Add a step command to build an sdist for a set of sources.
Update the build and build-sequence commands to produce an sdist as
well as a wheel when building something.
Update the bootstrap command to create sdists for everything that is
bootstrapped.
Fixes #67
=> feature: make a new sdist after running prepare_source

src/fromager/sdist.py
The dependencies are a set, and we might get them in different orders from
different invocations. Sorting the values makes the processing order
consistent and the build order output from run to run is therefore easier
to compare.
=> sort dependencies before recursing for consistent output

src/fromager/__main__.py, src/fromager/clickext.py, src/fromager/commands/bootstrap.py, src/fromager/commands/build.py, src/fromager/commands/build_order.py, src/fromager/commands/step.py
The new parameter type `ClickPath` is a subclass of `click.Path` that returns a pathlib.Path instead of a path-like object. All path paramemter now use `ClickPath` for handling input.
`PackageVersion` is a string input field that converts a version string to a packaging `Version` class with error checking.
=> Define custom click params for path and versions

.github/workflows/check.yaml, pyproject.toml, tox.ini
- add `mypy` checker to tox
- configure mypy to ignore packages without type annotations and type stubs
- add mypy checker to GHA (ignoring errors)
=> Configure mypy checker in tox and GHA

src/fromager/server.py, src/fromager/vendor_rust.py, src/fromager/wheels.py
`external_commands.run()` accepts a `list[str]`. Convert all occurances of `pathlib.Path` to `str`.
=> Convert Path to str for external_commands.run()

docs/customization.md, src/fromager/overrides.py, tests/test_overrides.py
Add support for organizing patches in subdirectories
instead of just prefixed with the source directory
name to avoid collisions when we have different source
directory names for different variants of the same
package.
Fixes #114
=> look for patches in subdirectories

docs/customization.md, pyproject.toml, src/fromager/example_override.py, src/fromager/resolver.py, src/fromager/sdist.py, src/fromager/sources.py, tests/test_resolver.py, tests/test_sdist.py
Some overrides are for doing things like building from a fork of a
project with fixes that aren't upstream. In those cases, the builder
might have to determine the version in some way other than looking at
pypi.org. Provide a hook for that, and include a sample implementation
that uses tags on github.com.
Resolves #103
=> feature: let overrides do version resolution

src/fromager/overrides.py, src/fromager/wheels.py, tests/test_overrides.py
fixes #115 
Instead of initializing `extra_environ` as an empty dictionary we can initialize it with whatever environment variables the current process has access to. This keeps the flexibility of overriding these variables later on using the .env per package files or plugins.
=> fix: pass environment variables from caller to build steps

src/fromager/sources.py
download_source() tries to resolve the source using multiple
servers. As part of the trial loop, it captures exceptions, logs them,
and continues with the next server. When there is a coding error in a
plugin, the capture behavior can mask the error. Instead of trapping
all exceptions, only catch the ones coming from resolvelib that are
also caught, and re-raised, in resolve_dist().
=> trap fewer exceptions when resolving a dependency

README.md, src/fromager/resolver.py
fixes #118 
If `GITHUB_TOKEN` is defined in the current environment then use it to create an authenticated instance of GitHub client and then use it in the resolver.
=> Added credentials for GitHub Resolver

src/fromager/sdist.py, tests/test_sdist.py
If we are given a requirements file as the set of toplevel dependencies,
it is reasonable to expect some entries to have marker expressions
controlling when the dependency is relevant. This change ensures
those expressions are evaluated so that dependencies for different
versions of python or other platforms are ignored.
=> evaluate marker expressions for toplevel dependencies

src/fromager/__main__.py, src/fromager/context.py, src/fromager/wheels.py
fixes #127 
Implemented the first method where a max number of jobs is passed to fromager via CLI and is exposed to the plugins via context
=> Add an option to pass the number of max jobs that are available

src/fromager/sdist.py
Make sure the log message is prefixed with the
package name and that the old and new requirement
specifiers are included.
=> clean up log message about constraints

src/fromager/commands/download_sequence.py
If the package has an override configured for download_source(), do
not try to download the sdist.
=> fix: only download sdist sources in download-sequence

docs/customization.md, e2e/post_build_hook/build/lib/package_plugins/post_build.py, e2e/post_build_hook/pyproject.toml, e2e/post_build_hook/src/package_plugins/post_build.py, e2e/test_build.sh, src/fromager/commands/build.py, src/fromager/hooks.py
Add a new extension point for plugging in after a
wheel is built. The hook should have enough
information to, for example, publish the newly
build sdist and wheel to a package index.
=> feature: post-build hooks

e2e/test_bootstrap.sh, src/fromager/context.py, tests/test_context.py
When we generate the constraints file, include a
comment for each package explaining where the
dependency came from.
=> add dependency information to constraints file

src/fromager/overrides.py, tests/test_overrides.py
Require patches to be organized into directories
by removing the old behavior allowing them all to
be in the `overrides/patches` directory.
=> remove legacy patch handling

docs/customization.md
We were missing docs for both get_build_sdist_dependencies() and build_sdist().
Fixes document the override for creating a source distribution #129
=> document override functions related to building sdist

src/fromager/sources.py
We had a package server set up for Fedora and were using it in the early prototypes, but it should not be included in the real versions of Fromager, now.
Fixes remove fedora package index from built-in sources #132
=> remove fedora package index from default resolver

tests/test_constraints.py
Ensure that if we have a requirement `foo[bar]>=1.0` and constraint `foo==1.1` then we get a new requirement `foo[bar]==1.1` back i.e. the extra `bar` shouldn't be removed
=> Add unit test to ensure that extras are applied even with constraints

src/fromager/commands/download_sequence.py, src/fromager/dependencies.py, src/fromager/sdist.py, src/fromager/sources.py
Add an option to download wheels to
download-sequence. This is useful for
pre-populating a development environment with
built wheels to avoid building expensive
dependencies when debugging the bootstrap logic.
Fixes #153
=> feature: add wheels to download-sequence

src/fromager/commands/download_sequence.py, src/fromager/sdist.py
When download-sequence tries to download pre-built
wheels, sometimes it finds packages that are only
available as source distributions. We can ignore
those errors because we will build the wheels
ourselves.
=> catch errors when trying to download wheels from cli

e2e/test_bootstrap.sh, src/fromager/context.py, tests/test_context.py
In this commit, I have created a helper to process duplicate entries in constraints.txt file and shift those to the start of the file as per discussion in https://github.com/python-wheel-build/fromager/issues/151
=> Find duplicates from constraints.txt

docs/customization.md, src/fromager/commands/list_overrides.py, src/fromager/overrides.py, src/fromager/settings.py, src/fromager/sources.py, tests/test_overrides.py, tests/test_settings.py, tests/test_sources.py
Fixes #138 
User can provide a mapping of package to download source url in `settings.yaml`:
```yaml
download_source:
torch:
url: "https://github.com/pytorch/pytorch/releases/download/v${version}/pytorch-v${version}.tar.gz"
rename_to: "torch-${version}"
```
User can define a predefined url for a package from which all its sources will be downloaded from. Optionally they can rename the downloaded sdist to whatever they want.
The only supported template variables are: `version`. `version` is replaced by the version returned by the resolver.
=> Give the user an option to use predefined urls to download sdists from

src/fromager/sources.py
This commit makes `_patch_cource()` method public by removing the trailing `_` in function definition and all its subsequent calls. This has been done as per description of issue: https://github.com/python-wheel-build/fromager/issues/150
=> Removed trailing _ from _patch_source method

src/fromager/commands/bootstrap.py, tests/test_bootstrap.py
The requirements files are always passed from click as a sequence, even
if there is only one value. We need to iterate over them and convert
the filename to a string and parse each file individually. This change
fixes the parsing function and updates the unit test to ensure that it
works correctly by actually trying to parse files instead of mocking the
return value.
=> fix reading requirements files for bootstrapping

.github/workflows/test.yaml, .mergify.yml, e2e/bootstrap_extras.txt, e2e/test_bootstrap_extras.sh, src/fromager/sdist.py
If we're given a requirements file as input, we
might be iterating over a list of requirements
with marker expressions that limit their use to
specific platforms or python versions. Evaluate
the markers to filter out anything we shouldn't
build. Only apply the filter to toplevel
requirements (items without a why list leading up
to them) because other dependencies are already
filtered based on their markers in the context of
their parent, so they include values like the
parent's extras settings.
Fixes #182
=> fix filtering based on markers during bootstrapping

src/fromager/dependencies.py, src/fromager/sdist.py, tests/test_dependencies.py
fixes #167 
Before resolving and getting requirements for dependency resolution, it checks first to see if the requirements have been produced before and if they have then they are loaded in from the file they were written to instead of resolving them again.
=> Add caching to dependency resolution

src/fromager/overrides.py
We have been working on making most messages start
with the dist name, then a statement about the
status. Apply this to the code for looking up
plugins.
=> make logging for override lookups consistent with other calls

e2e/test_build_steps.sh, src/fromager/commands/build.py, src/fromager/commands/step.py, src/fromager/sdist.py, src/fromager/sources.py
Also reorder the function arguments a bit more
logically (the version is related to the
requirement).
=> add the build environment when calling build_sdist

pyproject.toml, src/fromager/sources.py, src/fromager/wheels.py, tests/test_entrypoints.py
The new entry point `fromager.override_methods` lists all fromager override methods by name and their default implementation. This allows consumers to get a list of known override methods and compare function signatures.
Also address some typing issues in override methods and helpers.
=> Feat: entry points with override methods

src/fromager/commands/download_sequence.py
Only download things from a place the user has specifically told us to look.
=> sequence-download: only download wheels from the specified wheel server

src/fromager/overrides.py, tests/test_overrides.py
=> fix: remove quotes if it surrounds the value of an environment variable

e2e/test_bootstrap.sh, src/fromager/__main__.py
The debug log can be quite verbose, so provide an
option for logging just error messages to a
separate file for easier review.
=> add optional error log

.github/workflows/test.yaml, .mergify.yml, e2e/stevedore_override/build/lib/package_plugins/stevedore.py, e2e/stevedore_override/pyproject.toml, e2e/stevedore_override/src/package_plugins/stevedore.py, e2e/test_pep517_build_sdist.sh, src/fromager/sources.py
Return the full path to the built file instead of
just the base name that is returned by the build
backend. Add an end-to-end test for building
sdists using pep517_build_sdist().
=> fix return value for pep517_build_sdist

src/fromager/commands/build.py
Convert the input string to a Version instance
before calling the real build code.
Fixes #210
=> ensure build commands pass version as class not str

src/fromager/resolver.py, tests/test_resolver.py
Resolves: #220 .
When working with bitsandbytes override, I found that our logic doesn't allow for resolving against both `include_sdists` and `include_wheels`.
/cc @dhellmann @tiran @shubhbapna
=> allow both include_sdists and include_wheels in resolution

src/fromager/requirements_file.py
part of #226 
Fixes the following errors:
```
src/fromager/requirements_file.py:29: error: Missing type parameters for generic type "dict"  [type-arg]
src/fromager/requirements_file.py:38: error: List comprehension has incompatible type List[dict[str, object]]; expected List[Environment]  [misc]
src/fromager/requirements_file.py:41: error: Argument 1 to "evaluate" of "Marker" has incompatible type "Environment"; expected "dict[str, str] | None"  [arg-type]
```
Need this to fix errors in dependencies.py but I am not combining the two together in one PR because dependencies.py has a lot of typing fixes
=> cleanup: fix typings for requirements_file.py

src/fromager/constraints.py
part of #226 
Fixes the following type errors:
```
src/fromager/constraints.py:19: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/constraints.py:22: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/constraints.py:54: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/constraints.py:54: error: Missing type parameters for generic type "dict"  [type-arg]
src/fromager/constraints.py:62: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/constraints.py:64: error: Argument 1 to "_organize_constraints" has incompatible type "list[Any]"; expected "dict[Any, Any]"  [arg-type]
```
=> cleanup: fix typings for constraints.py

.github/workflows/test.yaml, .mergify.yml, e2e/test_meson.sh, src/fromager/vendor_rust.py
`vendor_rust` now inspects `pyproject.toml` and looks for `setuptools-rust` and `maturin` in `[build-system]requires`. When `pyproject.toml` does not exist or does not list a Rust build plugin as requirement, then Rust crates are not vendored.
The change indirectly addresses the issue with Meson's broken Rust crates in `test cases/rust`.
=> Only vendor Rust when project uses setuptools-rust / maturin

src/fromager/vendor_rust.py
part of #226 
fixes the following error:
```
src/fromager/vendor_rust.py:149: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/vendor_rust.py:149: note: Use "-> None" if function does not return a value
src/fromager/vendor_rust.py:176: error: Missing positional argument "project_dir" in call to "vendor_rust"  [call-arg]
src/fromager/vendor_rust.py:183: error: Call to untyped function "test" in typed context  [no-untyped-call]
```
I don't think we were using the `test` function anywhere and it was just put to quickly test this module manually
=> cleanup: remove unused function from vendor_rust

src/fromager/commands/canonicalize.py, src/fromager/commands/download_sequence.py, src/fromager/commands/list_overrides.py, src/fromager/commands/server.py
part of #226 
fixes the following error in each file:
```
error: Function is missing a return type annotation  [no-untyped-def]
```
=> cleanup: fix typings in commands: canonicalize.py, download_sequence.py, list_overrides.py, server.py

requirements.txt, src/fromager/dependencies.py, src/fromager/external_commands.py
part of #226 
Fixes the following errors:
```
src/fromager/dependencies.py:33: error: Incompatible return value type (got "set[Requirement] | None", expected "set[Requirement]")  [return-value]
src/fromager/dependencies.py:73: error: Returning Any from function declared to return "Iterable[Requirement]"  [no-any-return]
src/fromager/dependencies.py:90: error: Incompatible return value type (got "set[Requirement] | None", expected "set[Requirement]")  [return-value]
src/fromager/dependencies.py:119: error: Returning Any from function declared to return "set[Requirement]"  [no-any-return]
src/fromager/dependencies.py:136: error: Incompatible return value type (got "set[Requirement] | None", expected "set[Requirement]")  [return-value]
src/fromager/dependencies.py:165: error: Returning Any …
```
=> cleanup: fix typings for dependencies.py and external_commands.py

src/fromager/wheels.py
part of #226 
fixes the following errors:
```
src/fromager/wheels.py:30: error: Call to untyped function "_createenv" in typed context  [no-untyped-call]
src/fromager/wheels.py:36: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/wheels.py:36: note: Use "-> None" if function does not return a value
src/fromager/wheels.py:42: error: List item 3 has incompatible type "Path"; expected "str"  [list-item]
src/fromager/wheels.py:54: error: Argument 1 to "run" has incompatible type "list[object]"; expected "list[str]"  [arg-type]
src/fromager/wheels.py:68: error: Argument "cwd" to "run" has incompatible type "Path"; expected "str | None"  [arg-type]
src/fromager/wheels.py:120: error: Missing type parameters for generic type "dict"  [type-arg]
```
=> cleanup: fix typings in wheels.py

src/fromager/hooks.py
part of #226 
fixes the following errors:
```
src/fromager/hooks.py:9: error: Need type annotation for "_mgrs" (hint: "_mgrs: dict[<type>, <type>] = ...")  [var-annotated]
src/fromager/hooks.py:28: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/hooks.py:36: error: Function is missing a return type annotation  [no-untyped-def]
```
=> cleanup: fix typings for hooks.py

src/fromager/__main__.py
part of #226 
fixes:
```
src/fromager/__main__.py:101: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/__main__.py:101: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src/fromager/__main__.py:174: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/__main__.py:174: note: Use "-> None" if function does not return a value
src/fromager/__main__.py:185: error: Call to untyped function "invoke_main" in typed context  [no-untyped-call]
```
=> cleanup: fix typings for __main__.py

requirements.txt, src/fromager/commands/bootstrap.py, src/fromager/commands/build.py, src/fromager/commands/download_sequence.py, src/fromager/progress.py
The bootstrap, build-sequence and download-sequence commands now use `tqdm` to show a progress bar. It's now easier to see how far along a long-running pipeline job has come.
=> Show progress bars

src/fromager/commands/build.py
part of #226 
fixes
```
src/fromager/commands/build.py:19: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/commands/build.py:54: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/commands/build.py:110: error: Argument 3 to "BuildEnvironment" has incompatible type "None"; expected "Iterable[Requirement]"  [arg-type]
src/fromager/commands/build.py:134: error: Argument "dist_version" to "run_post_build_hooks" has incompatible type "Version"; expected "str"  [arg-type]
src/fromager/commands/build.py:136: error: Argument "wheel_filename" to "run_post_build_hooks" has incompatible type "Path | None"; expected "Path"  [arg-type]
src/fromager/commands/build.py:139: error: Incompatible return value type (got "Path | None", …
```
=> cleanup: fix typing in command/build.py

.github/workflows/test.yaml, .mergify.yml, docs/customization.md, e2e/build_settings.yaml, e2e/test_build_settings.sh, src/fromager/commands/list_overrides.py, src/fromager/overrides.py, src/fromager/settings.py, src/fromager/sources.py, tests/test_overrides.py, tests/test_settings.py, tests/test_sources.py
fixes #191 
fixes #185 
fixes #184
=> feat: implement settings driven download and high level resolver customization

e2e/common.sh, e2e/constraints.txt, e2e/test_bootstrap.sh, e2e/test_bootstrap_constraint.sh, e2e/test_bootstrap_extras.sh, e2e/test_build.sh, e2e/test_build_order.sh, e2e/test_build_settings.sh, e2e/test_build_steps.sh, e2e/test_download_sequence.sh, e2e/test_meson.sh, e2e/test_optimize_build.sh, e2e/test_override.sh, e2e/test_pep517_build_sdist.sh, e2e/test_prebuilt_wheels_alt_server.sh, e2e/test_report_missing_dependency.sh, e2e/test_rust_vendor.sh, requirements.txt
Update our dependency and constrain dependency in CI.
In order to do that, apply a common startup script to each test script so we have a place to set up the constraints using values that should be common to each test.
=> deal with setuptools 72.0.0

src/fromager/sdist.py
We noticed that dependencies that were resolving to some different version were not actually being installed using that version. Here is my analysis of the bug:
[_maybe_install](https://github.com/python-wheel-build/fromager/blob/main/src/fromager/sdist.py#L492) is called after handling each requirement. If the resolved version is not none, then it checks whether the actual version matches the resolved version and if it doesn't then it installs it using [safe_install](https://github.com/python-wheel-build/fromager/blob/main/src/fromager/sdist.py#L517) but in`_maybe_install` it seems like we are passing the old requirement to `safe_install` instead of the resolved one: https://github.com/python-wheel-build/fromager/blob/main/src/fromager/sdist.py#L514
=> bug: fix installation of dependency by using the resolved_version instead of actual_version

src/fromager/commands/bootstrap.py
part of #226 
fixes:
```
src/fromager/commands/bootstrap.py:17: error: Need type annotation for "to_build" (hint: "to_build: list[<type>] = ...")  [var-annotated]
src/fromager/commands/bootstrap.py:38: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/commands/bootstrap.py:63: error: Argument 1 to "Requirement" has incompatible type "list[str]"; expected "str"  [arg-type]
```
=> cleanup: fix typings in commands/bootstrap.py

src/fromager/commands/build_order.py
part of #226 
fixes
```
src/fromager/commands/build_order.py:15: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/commands/build_order.py:15: note: Use "-> None" if function does not return a value
src/fromager/commands/build_order.py:28: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/commands/build_order.py:71: error: Incompatible types in assignment (expression has type "TextIO | Any", variable has type "TextIOWrapper")  [assignment]
src/fromager/commands/build_order.py:92: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/commands/build_order.py:102: error: Need type annotation for "dist_to_input_file"  [var-annotated]
src/fromager/commands/build_order.py:113: error: Incompatible …
```
=> cleanup: fix typings for command/build_order.py

src/fromager/sources.py
The `sources.resolve_dist()` function returns
`tuple[str | None, Version]`, not `tuple[str, str]`. The fix will allow me to enable type checking in our builder repo.
See: #226
=> Fix type annotations of `resolve_dist()`

src/fromager/overrides.py, tests/test_overrides.py
`.env` files can now contain comments to explain the meaning of an env var or to mark a todo. `extra_environ_for_pkg()` no longer fails when an `.env` file contains empty lines.
=> Allow empty lines and comment in env files

pyproject.toml, requirements-mypy.txt, tox.ini
- move `mypy` extras into a requirements file
- install `types-tqdm` to fix mypy error in progress.py
- use a different TOML style for optional-dependencies
- tox: install extra dependencies with `extras`
See: #226
=> Add mypy optional dependency and types-tqdm

e2e/test_build.sh, e2e/test_rust_vendor.sh, src/fromager/__main__.py, src/fromager/context.py, src/fromager/dependencies.py, src/fromager/external_commands.py, src/fromager/sdist.py, src/fromager/sources.py, src/fromager/vendor_rust.py, src/fromager/wheels.py, tests/test_external_commands.py, tox.ini
Prevent sdist and wheel build steps from accessing the internet. `externalcommand.run()` can use now run commands with unshare. `unshare --net --map-current-user` creates a new network namespace without access network.
Fixes: #263
=> Run sdist and wheel building with network isolation

src/fromager/sources.py, tests/test_sources.py
fixes #230 
The `version` parameter was not being used in the `_warn_for_old_patch` function and so has been removed after talking to @rd4398. it was introduced to the `patch_source` function only for it to be passed to the warn function and so can be removed safely
=> feat: apply generic patches for all versions of packages

src/fromager/commands/build.py, src/fromager/sdist.py
fixes #235 
It should be easy to toggle this option even via env variable by setting `FROMAGER_BUILD_SEQUENCE_SKIP_EXISTING=true` (see https://click.palletsprojects.com/en/8.1.x/options/#values-from-environment-variables:~:text=When%20using%20auto_envvar_prefix,is%20WEB_RUN_SERVER_HOST.)
I also moved `start_wheel_server` outside of the loop to avoid applying the `update_wheel_mirror` method twice per package
=> feat: add an option to skip building of wheel if it is exists on the wheel server

src/fromager/candidate.py, src/fromager/extras_provider.py, src/fromager/resolver.py
part of #226 
fixes:
```
src/fromager/extras_provider.py:24: error: Missing type parameters for generic type "AbstractProvider"  [type-arg]
src/fromager/extras_provider.py:27: error: Function is missing a type annotation  [no-untyped-def]
src/fromager/extras_provider.py:34: error: Function is missing a type annotation  [no-untyped-def]
src/fromager/extras_provider.py:41: error: Function is missing a type annotation  [no-untyped-def]
src/fromager/extras_provider.py:43: error: Call to untyped function "get_extras_for" in typed context  [no-untyped-call]
src/fromager/extras_provider.py:49: error: Function is missing a type annotation  [no-untyped-def]
src/fromager/extras_provider.py:52: error: Call to untyped function "get_base_requirement" in typed context  [no-untyped-call] …
```
=> cleanup: fix typings in extras_provider.py

.github/workflows/check.yaml, pyproject.toml, src/fromager/external_commands.py, src/fromager/vendor_rust.py, tests/test_constraints.py, tests/test_overrides.py, tests/test_sdist.py, tests/test_sources.py, tox.ini
Thanks to Shubh's relentless work, most files now pass MyPy type checker. It's time to ensure that new code does not introduce regressions.
- enforce successful MyPy runs in `tox.ini` and GitHub Actions
- ignore MyPy errors in files with known issues
- fix a bunch of low hanging fruits in tests
See: #226
=> Enforce MyPy type checks, ignore files with known issues

.github/workflows/check.yaml, .gitignore, .readthedocs.yaml, docs/Makefile, docs/cli.rst, docs/conf.py, docs/index.rst, docs/make.bat, docs/requirements.txt, tox.ini
Fixes: https://github.com/python-wheel-build/fromager/issues/217
References: 
https://sphinx-click.readthedocs.io/en/latest/examples/commands/
https://www.sphinx-doc.org/en/master/usage/quickstart.html
https://stackoverflow.com/questions/53668052/sphinx-cannot-find-my-python-files-says-no-module-named
=> Generating CLI documentation

src/fromager/commands/bootstrap.py, src/fromager/progress.py, src/fromager/sdist.py
The bootstrap command uses a recursive algorithm to fetch sources and to build sdists + wheels. The complete set of dependencies is unknown until all packages have been downloaded and built.
The bootstrap command now passes an optional `progressbar` object around. Each handler updates the total amount of items in the beginning of a loop, and notifies the progress bar when an item has finished.
=> Fix progress bar recursion in bootstrap command

src/fromager/sources.py, src/fromager/tarballs.py, tests/test_tarballs.py
Remove the prefix from the members of the tarballs
created by default for sdists.
Fixes #287
=> fix filenames in tarballs for sdists

src/fromager/external_commands.py, tests/test_external_commands.py
Add an exception type for network isolation errors
and raise that type instead of a simple
CalledProcessError when we are running with
network isolation and see a message that looks
like that is the problem. This fixes a problem
with running the tests on different versions of
Linux, where the actual error message from the
program run by the test might be different.
=> improve network isolation error handling

docs/conf.py, docs/customization.md, docs/index.rst, docs/requirements.txt
We can now see `customization.md` and `develop.md` rendered in our docs
=> rendering .md using myst-parser

requirements.txt, src/fromager/wheels.py
Fromager uses `elfdeps` to analyse the content of a wheel file and logs the library dependencies and provides.
Example output for `lxml-5.2.2-cp311-cp311-linux_x86_64.whl`
```
INFO: lxml: Requires libraries: libc.so.6, libexslt.so.0, libxml2.so.2, libxslt.so.1
DEBUG: lxml: Requires libc.so.6(GLIBC_2.3.4, GLIBC_2.4, GLIBC_2.2.5, GLIBC_2.14)
DEBUG: lxml: Requires libexslt.so.0()
DEBUG: lxml: Requires libxml2.so.2(LIBXML2_2.6.17, LIBXML2_2.5.2, LIBXML2_2.4.30, LIBXML2_2.9.0, LIBXML2_2.5.9, LIBXML2_2.6.0, LIBXML2_2.7.4, LIBXML2_2.6.15, LIBXML2_2.6.20, LIBXML2_2.6.5, LIBXML2_2.6.18, LIBXML2_2.6.10, LIBXML2_2.7.0, LIBXML2_2.6.24, LIBXML2_2.6.2, LIBXML2_2.6.16, LIBXML2_2.6.21, LIBXML2_2.6.32, LIBXML2_2.5.7, LIBXML2_2.6.1, LIBXML2_2.6.14, LIBXML2_2.6.23, LIBXML2_2.5.8)
DEBUG: lxml: Requires …
```
=> Show ELF provides and requires in logs

src/fromager/context.py, src/fromager/external_commands.py, src/fromager/finders.py
part of #226 
fixes
```
src/fromager/external_commands.py:32: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/external_commands.py:32: note: Use "-> None" if function does not return a value
src/fromager/context.py:138: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/finders.py:24: error: Function is missing a return type annotation  [no-untyped-def]
src/fromager/__main__.py:25: error: Call to untyped function "detect_network_isolation" in typed context  [no-untyped-call]
```
=> cleanup: fix misc types in context, external_commands and finders

src/fromager/sdist.py
The old message produced confusing output like
installed build_system wheel using
The new message will look like
installed build_system requirement wheel
or
installed build_system requirement wheel>1.0
=> clean up install message for build environment

docs/customization.md, pyproject.toml, src/fromager/dependencies.py, src/fromager/settings.py, src/fromager/sources.py, src/fromager/wheels.py, tests/test_settings.py
fixes #278 
had to tell mypy to ignore `settings.py` until #257
=> feat: add new `build_dir` field in settings

src/fromager/progress.py
part of #226 
fixes:
```
src/fromager/progress.py:10: error: Missing type parameters for generic type "tqdm"  [type-arg]
src/fromager/progress.py:27: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src/fromager/progress.py:32: error: Missing type parameters for generic type "Iterable"  [type-arg]
src/fromager/progress.py:32: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src/fromager/progress.py:40: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
```
=> cleanup: fix typings for progress.py

e2e/flit_core_override/pyproject.toml, e2e/test_override.sh, src/fromager/overrides.py, tests/test_overrides.py
On startup, log the package and version from which
any override plugins are being loaded.
=> show plugin package and version

pyproject.toml, src/fromager/extras_provider.py, src/fromager/resolver.py
part of #226 
fixes:
```
src/fromager/resolver.py:79: error: Need type annotation for "tags" (hint: "tags: set[<type>] = ...")  [var-annotated]
src/fromager/resolver.py:82: error: Incompatible types in assignment (expression has type "frozenset[Tag]", variable has type "set[Any]")  [assignment]
src/fromager/resolver.py:150: error: Incompatible return value type (got "tuple[str, ...]", expected "tuple[str]")  [return-value]
src/fromager/resolver.py:150: error: Argument 1 to "sorted" has incompatible type "Iterable[str] | None"; expected "Iterable[str]"  [arg-type]
src/fromager/resolver.py:155: error: Function is missing a type annotation  [no-untyped-def]
src/fromager/resolver.py:155: error: Signature of "get_preference" incompatible with supertype "AbstractProvider"  [override] …
```
=> cleanup: fix typings for resolver.py

docs/customization.md, src/fromager/__main__.py, src/fromager/settings.py, tests/test_settings.py
Support settings for individual packages in separate files for easier
sharing and management. This also makes it easier to set up jobs to test
builds of specific packages when their settings change, without building
packages that have no changes.
=> add package-specific settings files

.github/workflows/test.yaml, .mergify.yml, e2e/flit_core_override/pyproject.toml, e2e/post_build_hook/pyproject.toml, e2e/stevedore_override/pyproject.toml, pyproject.toml
There is no need to support Python 3.10 any more. Intel Gaudi software 1.17.0 now uses Python 3.11. The rest of the AI stack prefers 3.11, too.
=> Drop support for Python 3.10

src/fromager/settings.py
I am getting this warning when running the unit tests:
```
================================================================== warnings summary ===================================================================
tests/test_settings.py::test_load_package_files_precedence
tests/test_settings.py::test_load_package_files_precedence
/home/sbapna/projects/fromager/.tox/py/lib/python3.12/site-packages/fromager/settings.py:183: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
logger.warn(
```
=> cleanup: change warn to warning in settings.py

e2e/test_build.sh, e2e/test_report_missing_dependency.sh, e2e/test_rust_vendor.sh, src/fromager/__main__.py, src/fromager/context.py, src/fromager/sdist.py, src/fromager/wheels.py, tests/conftest.py, tests/test_context.py, tests/test_sdist.py
If we're given a constraints file to decide which build dependencies to
use, apply those same constraints during installation. This ensures that if
the private wheel server has multiple versions of a package, we use the
right one to do the build.
=> pass constraints file when installing build dependencies

e2e/test_download_sequence.sh, src/fromager/commands/download_sequence.py
We use a build-order file to know what to
download, but we don't have to wait for one
download to complete to start the next one. Use
threads to download several packages in parallel.
Set a limit, but let the user control the limit
with a command line option.
=> download multiple packages in parallel in download-sequence

.github/workflows/test.yaml, .mergify.yml, e2e/test_extra_metadata.sh, requirements.txt, src/fromager/wheels.py
fixes #319 
We will create a `BUILD` file in the `.dist-info` directory of the wheel. This file is of TOML format and contains the entire settings of the package by default. There is an option for the user to include more data in this file by defining a plugin.
Additionally, I added the build system, build backend and build sdist requirements file (hope is that we can use this later to speedup bootstrapping)
=> feat: add extra metadata files while building wheels

src/fromager/wheels.py
- use `parse_wheel_filename()` function to parse a wheel file name
- bump missing dist-info logger from debug to error. This should not happen.
=> Use parse_wheel_filename() in add_extra_metadata

.github/workflows/test.yaml, .mergify.yml, e2e/mergify_lint.py, e2e/test_rust_vendor.sh
In addition to updating the actual GitHub action settings, this PR adds output to the linter so it prints a full list of rules that are expected for mergify, to make it easy to update that configuration file.
Fixes #332
=> enable CI on macos

.github/workflows/test.yaml
I am having trouble debugging macos failures and the only way I can do that is via github actions since I don't have access to a mac machine
=> upload logs on e2e failures to help debug

.github/workflows/test.yaml
artifact upload fails due to naming conflicts: https://github.com/python-wheel-build/fromager/actions/runs/10458484064/job/28960435191#step:7:18
=> fix artifact naming conflicts

.github/workflows/test.yaml, .gitignore, e2e/common.sh, pyproject.toml, requirements-test.txt, tests/test_dependencies.py, tox.ini
- Add `cov.pth` file and `COVERAGE_PROCESS_START` to track coverage of
subprocesses and e2e tests
- e2e tests set `COVERAGE_PROCESS_START` and run `command_pre` hooks
- Configure mapping of file paths for coverage
- Add step to combine coverage results in GHA
- Use plain `coverage` instead of `pytest-cov`. The pytest plugin
interfers with parallel coverage collection.
- Fix `test_dependencies` to actually run tests
=> Improve coverage reporting

src/fromager/sdist.py
fixes #302 
With the pydantic stuff in, #302 was essentially done (thanks @tiran!). This PR is to just start using the override while bootstrapping
=> feat: use prebuilt wheel server url override while bootstrapping

src/fromager/candidate.py, src/fromager/request_session.py, src/fromager/resolver.py, src/fromager/sources.py
Fixes: https://github.com/python-wheel-build/fromager/issues/361
=> Fromager 361: Requsts Session Object

.github/workflows/test.yaml
Fixes our broken github actions for coverage. It was because there was a breaking change release for the upload-artifacts github action which now ignores hidden files by default https://github.com/actions/upload-artifact/releases/tag/v4.4.0
=> fix: include hidden files when uploading coverage artifacts

docs/customization.md
=> docs: update docs to include how fromager skips downloading prebuilt wheels

docs/using.md, e2e/test_build_order.sh, src/fromager/commands/build.py, src/fromager/commands/download_sequence.py
fixes #374 
fixes #92 
Breaking change in the `build-sequence` command: it doesn't need the sdist_server_url arg anymore
=> fix: use download links from build order file in download sequence and build sequence instead of resolving again

docs/customization.md, e2e/build_settings/stevedore.yaml, src/fromager/packagesettings.py, src/fromager/sources.py, tests/test_packagesettings.py, tests/test_sources.py, tests/testdata/config-0.27/expected/torch.yaml, tests/testdata/config-0.27/settings.yaml, tests/testdata/context/overrides/settings/test_pkg.yaml
fixes #385 and also adds the nit picks from #384 
I know we discussed renaming fields in settings such that they are decoupled from their corresponding override but i think in this case `resolve_source` is a good name :)
=> fix: rename `resolver_dist` to `resolve_source` and pass output dir to `download_source`

requirements-mypy.txt, requirements.txt, src/fromager/__main__.py, src/fromager/context.py, src/fromager/packagesettings.py, src/fromager/wheels.py, tests/conftest.py, tests/test_packagesettings.py, tests/testdata/context/overrides/settings/test_pkg.yaml
The configuration for parallel build jobs can take available memory into account. Scaling factors for memory and CPU cores can be set per package.
- `--jobs` now sets the maximum number of cores to use (default: all cores)
Per package override is configured in `settings/mypackage.yaml`
```yaml
build_options:
cpu_scaling: 4
memory_scaling: 4
```
=> Redesign parallel build configuration

src/fromager/packagesettings.py, src/fromager/wheels.py, tests/test_packagesettings.py, tests/testdata/context/overrides/settings/test_pkg.yaml
Use `DIST_EXTRA_CONFIG` env var to configure `setuptools` to use parallel builds in `build_ext`. This speeds up compilation of packages such as Cython. The feature is disabled by default, because it breaks some packages like Numba 0.60.0.
Apply package env variables last. Package configuration can now override variables like `MAX_JOBS`.
=> Improve parallel job configuration

src/fromager/context.py
The build system changes the CWD and passes the input constraints file to pip subprocess.
=> Fix: Make context.input_constraints_file absolute

docs/customization.md, e2e/build_settings/stevedore.yaml, src/fromager/commands/migrate_config.py, src/fromager/packagesettings.py, src/fromager/sources.py, tests/test_packagesettings.py, tests/test_sources.py, tests/testdata/config-0.27/expected/torch.yaml, tests/testdata/config-0.27/settings.yaml, tests/testdata/context/overrides/settings/test_pkg.yaml
The option is called `resolver_dist`, not `resolve_source`. Rename helper properties and function to match the names of Fromager 0.27.
Fix config migration when a variant block is None instead of empty mapping.
=> Fix resolver_dist and config migration

docs/customization.md, src/fromager/packagesettings.py, src/fromager/pyproject.py, src/fromager/sources.py, tests/test_packagesettings.py, tests/test_pyproject.py, tests/testdata/context/overrides/settings/test_pkg.yaml
- add missing pyproject.toml
- add or update `[build-system] requires`
Requirements in `update_build_requires` are added to `[build-system] requires`. If a requirement name matches an existing name, then the requirement is replaced.
Requirements in `remove_build_requires` are removed from `[build-system] requires`.
Fixes: #260
Fixes: #274
=> Fixer for pyproject.toml build-system settings

.readthedocs.yaml, docs/conf.py, docs/config-reference.rst, docs/index.rst, docs/requirements.txt, pyproject.toml, src/fromager/packagesettings.py, tox.ini
Use autodoc-pydantic to generate some
configuration reference info.
Add some example YAML to docstrings for the models
included.
Add a [docs] extra for dependencies for building
documentation.
=> add auto-generated config reference documentation

e2e/test_bootstrap_extras.sh, src/fromager/overrides.py, src/fromager/sources.py, tests/test_overrides.py, tests/test_sources.py
Require patch directories be named using the override module form of the
name of the package being patched. In addition to being more predictable,
this allows us to simplify the logic for detecting patches for other
versions of a project that are not being applied.
Standardize the naming of unpacked source distributions to make the name
predictable.
We log the individual filenames when patches are applied, but if we do not
have a patch there is no indication that we tried to patch the source at
all.
Fixes #421
=> standardize patch directories using override module names

e2e/constraints.txt, requirements.txt
The setuptools issue introduced in 72.0.0 has been fixed in later
releases, so move our minimum past the bad release series and remove the
cap to allow newer versions.
=> raise setuptools minimum version and remove cap

docs/conf.py, docs/hooks.rst, docs/index.rst, src/fromager/dependencies.py, src/fromager/finders.py, src/fromager/resolver.py, src/fromager/sources.py, src/fromager/wheels.py, tox.ini
Add a custom `autofromagerhook` ReST directive to document Fromager hooks and their signatures. The intersphinx links are used to reference documentation of stdlib, packaging, and pyproject hooks types.
Also renames `_check_archive_name_in_settings` and adds two dummy default functions for documentation.
=> Add autodoc for hooks functions

src/fromager/commands/bootstrap.py
Using env to set options uses the internal option name. make both the internal name and option name match
=> fix: rename previous bootstrap option

.gitignore, docs/conf.py, docs/example/Containerfile, docs/example/bootstrap.sh, docs/example/constraints.txt, docs/example/overrides/patches/pydantic_core-2.18.4/0001-rust-version.patch, docs/example/requirements.txt, docs/getting-started.rst, docs/index.rst
Add an example of how to bootstrap a set of wheels and fix one that does not build immediately.
Related to #218
=> add a "getting started" guide

src/fromager/build_environment.py, src/fromager/dependencies.py, src/fromager/finders.py, src/fromager/hooks.py, src/fromager/pyproject.py, src/fromager/resolver.py, src/fromager/sdist.py, src/fromager/server.py, src/fromager/sources.py, src/fromager/wheels.py
Move imports of `context` and `build_environment` modules to `if typing.TYPE_CHECKING` blocks and introduce `from __future__ import annotations`. Most modules need these modules just for type annotations. This avoids import cycles in the future.
=> Add __future__.annotations and delayed imports

docs/hooks.rst, src/fromager/build_environment.py, src/fromager/packagesettings.py, src/fromager/sources.py, src/fromager/wheels.py, tests/test_packagesettings.py
The logic to run a command in a virtual environment has been moved from `build_wheel()` function into `BuildEnvironment.run()` method. It allows users to run any program in the context of a virtual environment.
The `PackageBuildInfo.get_extra_environ()` method applies all 
package-related env vars and optionally `BuildEnvironment` virtual env 
vars `PATH` and `VIRTUAL_ENV`. Before, parallel job settings were only 
applied for wheel building. Package env did not have access to modified
`PATH` and `VIRTUAL_ENV`.
=> Add run method to BuildEnvironment

src/fromager/sources.py
When a resolver provider is defined the sdist type should still be override since ` download-sequence` currently does not support such plugins
=> fix sdist type to be override if provider plugin is defined

tests/test_dependencies.py
When testing dependencies module it was creating .txt files in the directory where I have cloned fromager. This PR fixes that
=> fix: patch out _write_requirements_file when test dependencies module

requirements.txt, src/fromager/commands/build.py, src/fromager/dependency_graph.py
The `build-sequence` command now prints summary tables at the end. There is one table for built, pre-built, and skipped entries. The tables contain name, version, and source url. They are rendered as Markdown and also saved to a file in the work directory.
The table is generated with `rich`. The package is well-known, maintained, and comes with more useful feature for future enhancements, e.g. `rich.tree`.
Fixes: #272
Fixes: #438
=> Show a summary table in build-sequence and bootstrap

src/fromager/commands/build.py
This commit creates build log file before post build hook
Fixes: https://github.com/python-wheel-build/fromager/issues/447
=> Create build log file before post build hook

src/fromager/overrides.py
Fixes: https://github.com/python-wheel-build/fromager/issues/409
This commit adds log statements to the `find_and_invoke` method to log arguments and return value of the override method
=>  Log return value of override methods

src/fromager/packagesettings.py, tests/test_packagesettings.py
If MAKEFLAGS is undefined, MAKEFLAGS is set to " -j{number of cpus}", for example, " -j8".  This results in an error when cutting-and-pasting commands from the bootstrap.log to the command line.
(app-root) /work$ MAKEFLAGS= -j192 CMAKE_BUILD_PARALLEL_LEVEL=192 MAX_JOBS=192 VIRTUAL_ENV=/work-dir/torch-2.4.1/build-3.11.7 PATH=/work-dir/torch-2.4.1/build-3.11.7/bin:/usr/lib64/ccache:/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin USE_FFMPEG=0 USE_KINETO=1 USE_LEVELDB=0 USE_LMDB=1 USE_OPENCV=0 LLVM_SYSPATH=/usr/lib64/llvm-aotriton LLVM_INCLUDE_DIRS=/usr/lib64/llvm-aotriton/include LLVM_LIBRARY_DIR=/usr/lib64/llvm-aotriton/lib OPENBLAS_NUM_THREADS=1 CMAKE_ARGS=-DUSE_CUDA=OFF PYTORCH_BUILD_VERSION=2.4.1 PYTORCH_BUILD_NUMBER=0 …
=> Fix MAKEFLAGS -j argument

src/fromager/external_commands.py
`external_commands.run()` now quotes environment values, too. This enables copy and pasting when an environment variable contains spaces.
See: #455
=> shlex.quote environment values

src/fromager/build_environment.py, src/fromager/commands/bootstrap.py, src/fromager/commands/build.py, src/fromager/commands/download_sequence.py, src/fromager/commands/step.py, src/fromager/dependencies.py, src/fromager/resolver.py, src/fromager/sdist.py, src/fromager/sources.py, src/fromager/wheels.py, tests/test_build_environment.py, tests/test_dependencies.py, tests/test_sources.py
Import API functions no longer accept positional arguments and only support keyword arguments. This makes the code more reliable, readable, and prepares the functions for the `timeit` decorator.
Related: #408
Related: #445
=> Use keyword-only args for API functions

src/fromager/clickext.py, src/fromager/commands/graph.py, src/fromager/dependency_graph.py, src/fromager/requirements_file.py, tests/test_requirements_file.py
fixes #462 
Didn't get the bonus marks for converting to dot file : (
=> add a graph why command to explain why certain package appears in the graph

requirements.txt, src/fromager/resolver.py
Fromager uses `PyGithub` to retrieve a list of tag names and tarball URLs from GitHub. The feature can be implemented a with a few lines of code and requests. `PyGithub` depends on several packages with extension modules: `cffi`, `cryptography`, `PyNaCl`, and `wrapt`. All packages except for `cffi` don't have pre-built wheels for ppc64le and s390x on PyPI. Fewer platlib packages makes Fromager easier to run on these architectures.
The change removes support for `GITHUB_TOKEN` auth. We have never needed it in upstream or downstream of Fromager.
The remaining packages with mandatory extension are `psutil` and `pydantic_core`. `psutil` has a small C extension and no pre-built binaries for ppc64le and s390x. `pydantic_core` and its build dependency `maturin` are written in Rust. Upstream …
=> Remove dependency on PyGithub

.github/workflows/test.yaml, src/fromager/external_commands.py, src/fromager/run_network_isolation.sh, tests/test_external_commands.py
Some software like OpenMPI's `mpicc` do not work correctly without a loopback device. Replace the `unshare` call with a wrapper script that combines `unshare -rn` and `ip link set lo up` before `exec`-ing the final command.
`unshare` is a `util-linux-core` command and therefore available pretty much in all Linux distributions.
=> Fix: enable loopback device in network isolation

docs/customization.md, src/fromager/packagesettings.py, tests/test_packagesettings.py, tests/testdata/context/overrides/settings/test_pkg.yaml
Env vars in `package.yaml` now support default values with shell-like syntax `${NAME:-}` and `${NAME:-somedefault}`.
=> Add support for `${NAME:-somedefault}` syntax

src/fromager/dependencies.py
fixes #481 
Passes `extra_environ` as an argument to get build dependency hooks instead of getting them from settings directly. This will allow plugins to dynamically add more env variables
=> expose extra_environ argument in get build dependency hooks

src/fromager/bootstrapper.py, src/fromager/build_environment.py, src/fromager/requirements_file.py, src/fromager/resolver.py, src/fromager/sources.py, src/fromager/wheels.py, tests/test_build_environment.py, tests/test_resolver.py, tests/test_sources.py
fixes #359 
Summarizing the needs from #358 (and from our previous calls)
- we shouldn't use caching for install type requirements because we always want the latest version that matches the reqs and constraints and we cannot guarantee that the latest version will exist in the cache. For example:
- first we resolve `numpy<2` which ends up populating the cache with say `numpy==1`. Then we want to resolve `numpy>=1` as an install type req. if we end up using the cache it would return `numpy==1` even though there is a `numpy==2` that we can use.
- we want install type reqs to be the latest possible version so that they have the latest possible cve fixes in them
- the cache is something internal to the resolver and should not be influenced directly by the caller of the resolver
=> feat: add caching to resolver

src/fromager/commands/lint.py
`actual_package_name` is not defined for the else block and so it always ends up erroring out when using unversioned patches directory
=> fix linter for generic patches directory

docs/customization.md, src/fromager/overrides.py, src/fromager/packagesettings.py, src/fromager/sources.py, tests/test_overrides.py, tests/test_packagesettings.py, tests/test_sources.py
Fromager now supports variant-specific patches in additional to versioned and unversioned patches. Variant-specific patches are in subfolders, e.g. `atches/test_pkg-1.0.2/cpu/005-cpuver.patch`.
Patch files are sorted alphanumerically by their *base* name, not their full path. This allows users to sort versioned/unversioned and plain/variant patches as they like.
Internal changes: `sources.patch_source()` now uses `PackageBuildInfo` to get patches. `patches_for_requirement()` has been removed.
Fixes: #486
=> Implement variant-specific patches

src/fromager/packagesettings.py, tests/test_packagesettings.py
Fix a problem introduced in #488 that could cause packages with a prefix
common to another package's full name to have their patches included
when scanning for patches of the package with the shorter name. For
example, with patches for both 'foo' and 'foo-bar' when patches for
'foo' are loaded they would have included patches for 'foo-bar'.
=> ensure packages with common prefixes do not mix patches

src/fromager/__main__.py, src/fromager/resolver.py
Change the behavior of the main program to show only the summary of an
exception and not the full traceback, by default. Add a `--debug` flag to 
expose the traceback information for debugging, if needed.
Fixes #181
=> do not show full traceback by default

docs/how-to.md, docs/index.rst
Fixes: https://github.com/python-wheel-build/fromager/issues/398
This commit attempts to add documentation for the `--jobs` option and package build settings like` new cpu_cores_per_job`  and  `memory_per_job_gb`
This commit also creates a separate section titled "How To"  in the official fromager docs where the above content can be found.
=> Doc: jobs option and package build setting

src/fromager/__main__.py
This commit fixes a bug related to error message handling. The `main` will now exit using `sys.exit(1)` when there is an error
=> Bug Fix: terminate when error is encountered

src/fromager/commands/bootstrap.py, src/fromager/commands/graph.py
fixes #500 
print why the conflicting dependencies were being pulled in at the end of bootstrap
=> improve error message when generated constraints file is invalid

e2e/test_bootstrap_cache.sh, src/fromager/bootstrapper.py, src/fromager/wheels.py
fixes #507 
We save at the very least the cost of spawning a new process to unpack the wheel for each dependency
=> use zipfile library instead of wheel command to unpack a wheel

e2e/test_bootstrap_cache.sh, src/fromager/bootstrapper.py, src/fromager/sources.py
fixes #510 
Resolving and then immediately detecting if we have seen the dependency allows us to avoid paying the cost of trying to download and verify the sdist tarball each time that dependency is requested.
On our downstream systems just torch itself was spending 3 minutes total in `download_source` in a single bootstrap run with all performance features enabled. This brings it down to 5 seconds for torch (didn't measure it for other dependencies)
=> Detect if we have already seen the dependency before downloading sources

src/fromager/dependency_graph.py, tests/test_graph.py
due to cycles graph traversal would cause maximum recursive depth reached error
=> fix cycles in when traversing graph

src/fromager/commands/bootstrap.py, tests/test_bootstrap.py
Fixes : https://github.com/python-wheel-build/fromager/issues/524
=> Bug Fix: Duplicates are written to constraints file during bootstrapping

e2e/test_build_order.sh, src/fromager/commands/build.py
Machine readable version of the current markdown table
Useful in pipeline environments to filter skipped or prebuilt packages from a subsequent twine publish
Signed-off-by: Pris Nasrat <pris.nasrat@chainguard.dev>
=> Add build-sequence-summary.json

src/fromager/commands/bootstrap.py, tests/test_bootstrap.py
We're seeing some cases downstream where fromager
fails with an exception because it tries to remove
something from the unresolved dependency list when
the item isn't in the list. This seems to be
caused by having multiple candidate versions for a
package where both versions could be used by all
consumers.
This change resolves the issue by stopping the
resolution loop when we find a version of a
package that can work for all consumers. The loop
now iterates from the newest version to the
oldest, to ensure we choose the newest package
that works.
There is also some error handling in case this fix
is not sufficient to eliminate the original
ValueError.
I also noticed that a log message that we supposed
to print debug info about the candidate versions
was using the wrong list variable so it …
=> fix some issues writing the constraints file during bootstrap

src/fromager/constraints.py, src/fromager/context.py, src/fromager/resolver.py, tests/test_constraints.py, tests/test_resolver.py
Refactor and modify the API of `fromager.constraints` module to prepare the code for multiple constraints files.
The `Constraints` class no longer takes an mapping of package name to `Requirement`. Instead it has a new method `add_constraints()` that takes one or more requirements strings. The method does not take `Requirements` object, because we might want to modify and merge constraints in the future.
The `load()` module-level function has been replaced by `Constraints.load_constraints_file()` method.
=> Refactor constraints module

src/fromager/versionmap.py, tests/test_versionmap.py
=> add VersionMap helper

src/fromager/vendor_rust.py
Fromager was vendoring crates from all `Cargo.toml` files in a project. This approach is causing issues for projects that have cargo files in tests and example directories.
The `vendor_rust()` function now only vendors crates from `Cargo.toml` in the project's root directory and additional cargo files listed in `tools.maturin` or `tools.setuptools-rust` entries.
Fixes: #529
=> Fix vendor Rust: limit to manifests from backend

e2e/test_bootstrap_constraints.sh, src/fromager/bootstrapper.py, src/fromager/packagesettings.py
This commit adds a debug message for `expected_build_tag` and logs the change log entries for debug
Further, new version of pbr released few days ago which breaks our e2e test for `test_bootstrap_constraints.sh`. The pbr version is now updated to `6.1.1` for the test
Signed-off by: Rohan Devasthale
=> Add debug message for expected build tag

src/fromager/run_network_isolation.sh
Unshare UTS namespace and set hostname to "localhost". Some build systems lookup "localhost". We didn't run into the problem, yet, because Fedora-based distros have `127.0.0.1 localhost` in `/etc/hosts`.
Thanks to Michał Górny @mgorny for suggesting the change.
=> network isolation: set hostname to localhost

.github/workflows/test.yaml, .mergify.yml, e2e/test_lint_requirements.sh, e2e/validate_inputs/constraints.txt, e2e/validate_inputs/invalid-requirements.txt, e2e/validate_inputs/requirements.txt, src/fromager/commands/__init__.py, src/fromager/commands/lint_requirements.py
This commit adds the `lint-requirements` command to fromager. 
This command can be used to check the formatting of `requirements.txt` and `constraints.txt` along with the entries in these files being valid or not.
The command can process multiple files at the same time.
Usage:
`fromager lint-requirements "path/to/constraints.txt" "path/to/requirements.txt"`
Signed-off by Rohan Devasthale
=> [Feat]: Add lint-requirements command

src/fromager/resolver.py
Implement the reporter API used by resolvelib so that the resolver can
report progress and explain why candidates are rejected.
Fixes #548
=> add logging to resolver

e2e/test_bootstrap_extras.sh, e2e/test_elfdeps.sh
Some packages used by the e2e tests have changed, so update the
tests to reflect the new naming.
=> fix: e2e test failures

src/fromager/packagesettings.py, src/fromager/wheels.py, tests/test_packagesettings.py, tests/test_wheels.py, tests/testdata/context/overrides/settings/test_pkg.yaml
PEP 517 config-settings are used to pass arbitrary settings to the wheel build backend. The Meson build backend uses the feature to customize builds, e.g. to change the BLAS and LAPACK backend of NumPy. Config-settings are needed to build matplotlib with system packages.
=> feat: Add PEP 517 config-settings option

src/fromager/bootstrapper.py, src/fromager/build_environment.py, src/fromager/requirements_file.py, src/fromager/resolver.py, tests/test_bootstrapper.py, tests/test_build_environment.py, tests/test_requirements_file.py
bootstrap was treating install requirements of build systems and build
backends as plain install requirements. Instead any installation
requirement of a build backend should be treated as a build requirement,
too.
The previous implementation of `RequirementType` enum was confusing and
had subtile bugs. It was surprising that one enum member was equal to
several other enum members. The `__ne__` implementation was wrong and
the presence of `__eq__` without a `__hash__` in the subclass broke
hashability.
```
>>> from fromager.requirements_file import RequirementType
>>> hash(RequirementType.BUILD)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'RequirementType'
>>> RequirementType.BUILD.__eq__(None)
NotImplemented
>>> …
```
=> Improve RequirementType enum, fix req_type in bootstrap

src/fromager/sources.py
Fromager was using the package's `build_dir` as sdist name. This lead to wrong and invalid sdist names for packages with a `build_dir` option. For example our downstream build of Triton has a sdist with file name `python.tar.gz` because it has `build_dir: python` setting.
=> fix: always use sdist name $name-$version.tar.gz

e2e/test_bootstrap_git_url.sh, e2e/test_bootstrap_git_url_tag.sh, e2e/test_pep517_build_sdist.sh, requirements-test.txt, src/fromager/sources.py
GitLab tar balls are not valid Python sdists because they are missing a `PKG-INFO` file. The file is required for `setuptools-scm` and for latest Twine. `ensure_pkg_info` helper ensures that a source tree has a minimal `PKG-INFO`.
=> Ensure PKG-INFO in sdists

src/fromager/build_environment.py
`virtualenv` behaves differently on Python >=3.12 than on <=3.11. On 3.12+ it does not install setuptools and wheel. Packages are suppose to declare these build requirements in their `pyproject.toml`. Some packages haven't been updated, yet. Let's always install setuptools and wheel.
Also disable downloads and updates of embedded wheels to prevent network access.
=> virtualenv: always install setuptools and wheel, no download

src/fromager/resolver.py, tests/test_resolver.py
Add better logging and exceptions in the resolver code to convey more information about what is happening when no match is found.
Log debug messages for cases like ignoring all candidate files or having no candidates at all.
Use standard ResolverException error types and use messages specific to the different cases for searching for different types of files (sdists or wheels).
Move all of the logic for checking version compatibility into is_satisified_by() method of the base class for more consistent logging via different paths.
=> improve error messages from resolver

src/fromager/overrides.py
We currently log when a plugin _does_ accept an argument. That information was useful in the past to debug the invocation code, but it is no longer needed and it makes the debug logs more verbose than necessary.
=> remove debug messages about arguments accepted by plugins

src/fromager/dependencies.py
It was not clear why a requirement was being ignored, so add more words to the message to try to make that clear.
=> improve wording of log message when filtering requirements

src/fromager/bootstrapper.py
There are cases where we rebuild dependencies during bootstrap, so we need to ensure the cleanup code is robust in the face of repeats. This change ensures that we do not try to delete the build environment directory if we think we have one, but it has already been cleaned up.
=> only delete build-env if it exists

.github/workflows/test.yaml, .mergify.yml, docs/customization.md, e2e/fromager_hooks/pyproject.toml, e2e/fromager_hooks/src/package_plugins/hooks.py, e2e/test_post_bootstrap_hook.sh, src/fromager/bootstrapper.py, src/fromager/hooks.py
Add a hook entry point invocation for after we have bootstrapped a package. It is given the source distribution filename and the wheel filename, just like for the post-build hook, except that the sdist can be None if the wheel is pre-built and the wheel can be None if we are bootstrapping in sdist-only mode.
=> add hook entry point for bootstrap

src/fromager/packagesettings.py, tests/test_packagesettings.py
Summary
This PR addresses incorrect behavior in the substitute_template function where missing variables without defaults were silently replaced with None, instead of raising a KeyError as expected.
Fixes: https://github.com/python-wheel-build/fromager/issues/553
Changes :
Fixed src/fromager/packagesettings.py:substitute_template logic to:
Only apply default values when explicitly specified using the :-default syntax.
Leave variables without defaults unresolved, allowing string.Template.substitute to raise a KeyError for unknown variables.
Added a test case to ensure a KeyError is raised when ${UNKNOWN} is used without a default and the variable is not in template_env.
Tests:
Added tests/test_packagesettings.py::test_substitute_template_key_error() to validate the raised exception …
=> fix: handle undefined variable in substitute_template

src/fromager/bootstrapper.py, src/fromager/build_environment.py, src/fromager/commands/step.py, tests/test_packagesettings.py, tests/test_wheels.py
Several place did not log the requirement name. Now virtual env and build dependency lines also log the name of the requirement.
=> fix: log requirement name in more places

src/fromager/__main__.py
In normal mode show the hour, minutes, and seconds. This lets someone get a sense of how long a step has been running, which is useful for some packages that take a long time to build.
In verbose mode, and in log files, show the full datetime. This is useful for logs that are saved and examined later.
=> add time to log messages

src/fromager/build_environment.py
By default, `pip install` also compiles byte code of all Python files. The step takes a while, especially for large packages like PyTorch. Disable byte code compilation to speed up installation of build dependencies. Byte code is now compiled on demand.
=> Don't compile bytecode of dependencies

e2e/common.sh, e2e/test_bootstrap_build_tags.sh, e2e/test_bootstrap_cache.sh, src/fromager/bootstrapper.py
This PR includes a little bit of refactoring of existing code and then it adds the behavior of looking in the wheel downloads and wheel builds directories for a wheel before checking the remote cache server.
Fixes #578
=> Bootstrap check local dir before cache server

requirements.txt, src/fromager/bootstrapper.py
In #586, I broke the way the metadata files are extracted by changing the output directory handling. This change restores the original logic.
=> fix issue with extracting metadata

src/fromager/commands/server.py
fix a typo in the help text for the `server` CLI.
=> fix typo in "server" help text

requirements.txt, src/fromager/build_environment.py
Most recent virtualenv version has removed the `--wheel` option and the bundled `wheel` package. Setuptools can now build wheels without the wheels package.
Uncap `virtualenv` package again.
=> virtualenv 20.31.0 has dropped --wheel option

src/fromager/bootstrapper.py, src/fromager/sources.py, src/fromager/wheels.py
Include the variant name in log lines of a few steps like sdist and wheel builds. This is useful when running multiple builds in parallel. In downstream we currently rely on the fact that builds have the variant name in some paths. This causes problems with caching and will go away.
=> Log variant name in a few places

src/fromager/build_environment.py
Remove the flag that causes us to use a bundled version of setuptools in the build virtualenv. That version is too old to build some packages, especially in the face of recent breaking changes that have been worked around in things that use setuptools.
Instead of using the bundled version, rely on the fact that in src/fromager/dependencies.py we set the default build backend requirements to include setuptools if there is no valid information in the pyproject.toml. This should ensure that we detect setuptools as a dependency of projects that are likely to use it because it is the default backend.
=> do not use bundled setuptools in virtualenvs

e2e/matplotlib_settings/cython.yaml, e2e/matplotlib_settings/matplotlib.yaml, e2e/matplotlib_settings/meson-python.yaml, e2e/matplotlib_settings/meson.yaml, e2e/matplotlib_settings/numpy.yaml, e2e/test_bootstrap_sdist_only.sh, src/fromager/dependencies.py, src/fromager/packagesettings.py, src/fromager/sources.py, src/fromager/wheels.py, tests/test_packagesettings.py, tests/testdata/context/overrides/settings/test_pkg.yaml
Pass `config_settings` to all hooks. This fixes sdist-only mode for `matplotlib`. The settings are now passed to
`prepare_metadata_for_build_wheel` and meson no longer attempts to download freetype when getting build metadata.
This change is backwards incompatible. `config_settings` is now a mapping of strings to list of strings. Before it was just a list of strings.
I'm including my `e2e/matplotlib_settings` files for future testing.
=> Fix: Pass config settings to hooks

e2e/test_bootstrap_git_url.sh, e2e/test_bootstrap_git_url_tag.sh, src/fromager/bootstrapper.py, src/fromager/commands/bootstrap.py, src/fromager/sources.py
This pull request addresses issue #632 by improving how Fromager handles requirements specified with Git URLs during the bootstrap process. The changes consolidate Git URL processing logic in the bootstrapper and ensure build dependencies are properly resolved before extracting version metadata.
- Move git url handling to bootstrapper  
Moves source resolution for requirements with git URLs into the bootstrapper, consolidating logic that was previously split between the sources module and bootstrapper. This ensures build dependencies are available before processing metadata.
- Move version resolution to method in bootstrapper  
Extracts version resolution logic into a reusable method in the bootstrapper to eliminate code duplication between bootstrap command and bootstrapper class.
- …
=> Fix Git URL handling for bootstrap from URL requirements

docs/using.md
Add comprehensive high-level process documentation for all three main
build modes in fromager:
- Bootstrap process: 8-step recursive dependency discovery and building
- Build command: 7-step single-package focused building
- Build-sequence command: batch processing with caching optimization
Each section explains the key steps, decision points, and outputs to help
newcomers understand when and how to use different build approaches.
[Created in part by Cursor and claude-4-sonnet](https://gist.github.com/dhellmann/fc7054e145619b6c7d1aae24097227d8)
Fixes: #538
=> docs(build): add detailed build process documentation

.gitignore, src/fromager/packagesettings.py, src/fromager/resolver.py, src/fromager/sources.py, src/fromager/wheels.py, tests/test_packagesettings.py, tests/test_resolver.py, tests/test_sources.py, tests/testdata/context/overrides/settings/test_pkg.yaml
A package can now ignore the upstream wheels' platforms when looking up distributions without an sdist on PyPI. The option only applies to packages that have `resolver_dist.include_wheels` enabled.
The flag allows to package versions that neither provide a sdist nor a binary wheel for the current platform, e.g. Torch builds on ppc64le. Torch does neither upload sdists nor does it provide ppc64le wheels on PyPI.
Fixes: #556
=> feat: Add option to ignore wheel platform in resolver

docs/how-tos/pre-release-versions.rst
This commit adds documentation for pre-release
verisons in the form of how-to in official fromager docs.
Closes: https://github.com/python-wheel-build/fromager/issues/661
=> Add documentation for pre-release versions

.gitignore, e2e/common.sh
When running the tests locally the coverage report data clutters up the working directory which makes the IDE file list messy. Provide a way to turn off coverage locally.
=> feat: make it possible to skip coverage reports

e2e/test_build_order.sh, e2e/test_build_parallel.sh, pyproject.toml, src/fromager/commands/build.py
The _is_wheel_built function was returning a boolean to indicate to the
caller whether the filename returned should be used. Change the function
to return a Path or None, so the caller only has to check the one
return value.
Return the full path to where we downloaded the wheel, or return None if
we do not download one. Add more logging to make it easier to follow
what is happening, especially when the candidate is not usable.
Log more information about what we are doing when we decide to download
a wheel vs. recognize that the wheel is present on the local server.
Update the e2e tests that look for specific log messages to match the
new patterns.
Remove duplicate calls to `update_wheel_mirror()` in `_build()`. At best they
are redundant, at worst they could change state twice.
=> fix handling of existing packages during build

src/fromager/resolver.py, tests/test_resolver.py
This commit adds support for PEP 592, items with `data-yanked` are skipped.
Fixes #690
=> Add support for PEP 592 data-yanked

src/fromager/bootstrapper.py, src/fromager/commands/build.py, src/fromager/wheels.py
The build commands like `build-sequence` were not using `pbi.wheel_server_url`. Under some conditions they were using wheels from an upstream server or requirement URL instead of the configured package wheel server.
The `wheels.get_wheel_server_urls()` handles this case correctly, but the current implementation is not usable for build command.
Refactor code:
- modify `get_wheel_server_urls()` to accept a cache wheel server url instead of a hard-coded URL.
- pass `cache_wheel_server_url` instead of `wheel_server_urls` in build commands
- use `get_wheel_server_urls()` in build commands
Fixes: #704
=> fix: use get_wheel_server_urls() in build command

src/fromager/commands/build.py, src/fromager/wheels.py
Use an `ExceptionGroup` to return information about all failed resolve attempts, so we can see which lookup failed.
=> chore: improve logging of resolve_prebuilt_wheel

pyproject.toml, src/fromager/build_environment.py, src/fromager/context.py, src/fromager/dependencies.py, src/fromager/wheels.py, tests/test_build_environment.py, tests/test_packagesettings.py, tests/test_wheels.py
The build environment is now managed with `uv` instead of `virtualenv` and `pip`. `uv venv` creates an almost empty virtual env without `pip` command. `uv pip install` uses a faster resolver, parallel downloads, and several caches. Wheels are unpacked in a cache directory and "installed" by hardlinking files. These tricks speed up bootstrapping and building substantially.
In downstream I have measured 4:30 minutes instead of 11 minutes for a bootstrap-parallel run with all wheels in the cache index.
Use PEP 517 API and pyproject `BuildBackendHookCaller` instead of `pip wheel` to build wheels. Fromager no longer needs pip in a build environment to build a package.
=> feat: use uv to manage build environment

src/fromager/commands/bootstrap.py, src/fromager/resolver.py
SpecifierSet parsing and matching takes a non-trivial amount of time. A bootstrap run can spend over 10% of its time in parsing and matching Python version requirements.
The resolver now uses an LRU cache for parsing and matching a Python version requirement.
From my test run with about 370 packages:
```
match_py_req LRU cache: CacheInfo(hits=331462, misses=1110, maxsize=200, currsize=126)
```
Fixes: #742
=> perf: cache Python requirement match

src/fromager/commands/bootstrap.py
Log cache hits with `debug` instead of `info` level.
See: https://github.com/python-wheel-build/fromager/pull/743
=> fix: Reduce log level for LRU cache info

docs/hooks.rst, src/fromager/context.py, src/fromager/dependencies.py, src/fromager/sources.py, src/fromager/wheels.py, tests/test_sources.py, tests/test_wheels.py
Fromager now validates the dist name and dist version part of sdist and wheel files. The canonicalized dist name must match the canonicalized requirement name. The public version versions must match, too. Validation is performed in `build_sdist`, `build_wheel`, and `default_get_install_dependencies_of_sdist` steps. The latter covers bootstrap in sdist-only mode.
The new checks prevent invalid and broken packages, e.g. `unknown-0.0` wheel or a wheel that has wrong version number.
=> feat: validate name and version of sdist and wheel

src/fromager/bootstrapper.py, src/fromager/build_environment.py, src/fromager/commands/build.py, src/fromager/commands/step.py, src/fromager/context.py, src/fromager/wheels.py
Refactor the code so `uv cache` is cleaned up after each batch of build wheels. Before there was a possibility that `uv cache clean` and `uv pip install` were running at the same time.
Fixes: #756
=> fix: don't run `uv cache clean` in parallel with `uv pip install`

.github/workflows/check.yaml, .github/workflows/test.yaml, e2e/test_build_order.sh, pyproject.toml, src/fromager/commands/build.py
The build command now reports skipped builds again. Commit 330958e introduced a regression and did not set `BuildSequenceEntry.skipped` attribute any more.
The internal `_build` command now returns a `BuildSequenceEntry` object instead of `tuple[pathlibPath, bool]`. This change allows us to track properties like skipped and prebuilt more easily.
Also refactored `BuildSequenceEntry` to be a frozen, ordered, and hashable data class. Instances of the class are compared, sorted, and hashed by name and version.
Fixes: #769
=> fix: report skipped builds

docs/how-tos/build-web-server.rst, src/fromager/__main__.py, src/fromager/context.py
Add a command line flag to let the user specify that there is an alternative web server running and serving the content of the wheels-repo so that fromager does not need to start its own internal server.
Fixes #768
=> feat: add --build-wheel-server-url option

src/fromager/dependencies.py, tests/test_dependencies.py
The name field of sdist metadata is not guaranteed to be canonicalized to the package's normalized name. Some packages have capitalization. The sdist and wheel file name paths are not affected by the problem. `parse_sdist_filename` and `parse_wheel_filename` return a `NormalizedName`.
- `default_get_install_dependencies_of_sdist` now calls `canonicalize_name()` to pass a normalized name to validation function.
- `validate_dist_name_version` now requires a `NormalizedName` as `dist_name` parameter.
- `validate_dist_name_version` have more information in the exception (based on Doug's PR 782)
- more tests
=> fix: normalize name in default_get_install_dependencies_of_sdist
